EmprestimosJogos/Controllers/AmigoController.cs
using EmprestimosJogos.Filters;
using EmprestimosJogos.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EmprestimosJogos.Controllers
{
    [FilterUsuario]
    public class AmigoController : Controller
    {
        EmprestimoContext contexto;
        public AmigoController() {
            contexto = new EmprestimoContext();
        }
        [HttpGet]
        public ActionResult AdicionaAmigo()
        {
            try
            {
                Amigo Amigo = new Amigo();
                return View(Amigo);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult AdicionaAmigo(Amigo Amigo){
            try {
                var amigoExistente = (from c in contexto.Amigo where c.cpf == Amigo.cpf select c).FirstOrDefault();
                if (amigoExistente == null)
                {
                    Amigo.ativo = true;
                    contexto.Amigo.Add(Amigo);
                    contexto.SaveChanges();
                    TempData["sucess"] = "Amigo salvo com sucesso";
                }
                else {
                    TempData["error"] = "Já existe um amigo com este cpf";
                    return View(Amigo);
                }
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao salvar o amigo";
            }
            return RedirectToAction("ListaAmigos");
        }

        [HttpGet]
        public ActionResult EditaAmigo(int id)
        {
            try { 
            Amigo Amigo = (from c in contexto.Amigo where c.id==id select c).SingleOrDefault();
            return View(Amigo);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult EditaAmigo(Amigo Amigo)
        {
            try
            {
                var amigoExistente = (from c in contexto.Amigo where c.cpf == Amigo.cpf && c.id!=Amigo.id select c).FirstOrDefault();
                if (amigoExistente == null)
                {
                    Amigo.ativo = true;
                    contexto.Entry(Amigo).State = System.Data.Entity.EntityState.Modified;
                    contexto.SaveChanges();
                    TempData["sucess"] = "Amigo salvo com sucesso";
                }
                else {
                    TempData["error"] = "Já existe um amigo com este cpf";
                    return View(Amigo);
                }
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao atualizar o cadastro do Amigo!";
            }

        
            return RedirectToAction("ListaAmigos");

        }

        [HttpPost]
        public ActionResult ExcluiAmigo(string idExcluir) {
            try {
                int id = int.Parse(idExcluir);
                var amigo = contexto.Amigo.Find(id);
                amigo.ativo = false;
                contexto.Entry(amigo).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                TempData["sucess"] = "Amigo " + amigo.nome + " foi excluído com sucesso";
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao excluir o cadastro do Amigo!";
            }

            return RedirectToAction("ListaAmigos");
        }

        [HttpGet]
        public ActionResult ListaAmigos()
        {
            try
            {
                var amigos = (from c in contexto.Amigo where c.ativo==true orderby c.nome select c).ToList();
                return View(amigos);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

EmprestimosJogos/Controllers/EmprestimoController.cs
using EmprestimosJogos.Filters;
using EmprestimosJogos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EmprestimosEmprestimos.Controllers
{
    [FilterUsuario]
    public class EmprestimoController : Controller
    {
        EmprestimoContext contexto;
        public EmprestimoController() {
            contexto = new EmprestimoContext();
        }
        [HttpGet]
        public ActionResult AdicionaEmprestimo()
        {
            try
            {
                ViewData["idAmigo"] = new SelectList((from c in contexto.Amigo where c.ativo == true orderby c.nome select c).ToList(), "id", "nome");
                var emprestados = (from c in contexto.emprestimo_jogo where c.status == "e" select c.Jogo).ToList();
                var jogos = (from c in contexto.Jogo where c.ativo == true orderby c.titulo select c).ToList();
                var jogosDisponiveis = jogos.Except(emprestados).ToList();
                ViewData["idJogo"] = new SelectList(jogosDisponiveis, "id", "titulo");
                emprestimo_jogo Emprestimo = new emprestimo_jogo();
                return View(Emprestimo);
            }
            catch (Exception e)
            {
                return RedirectToAction("ListaEmprestimos");
            }
        }

        [HttpPost]
        public ActionResult AdicionaEmprestimo(emprestimo_jogo Emprestimo){
            try {
                Emprestimo.data = DateTime.Now;
                Emprestimo.status = "e";
                contexto.emprestimo_jogo.Add(Emprestimo);
                contexto.SaveChanges();
                TempData["sucess"] = "Emprestimo salvo com sucesso";
            
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao salvar o Emprestimo";
            }
            return RedirectToAction("ListaEmprestimos");
        }

        [HttpGet]
        public ActionResult EditaEmprestimo(int id)
        {
            try {
                emprestimo_jogo Emprestimo = (from c in contexto.emprestimo_jogo where c.id == id select c).SingleOrDefault();
                ViewData["idAmigo"] = new SelectList((from c in contexto.Amigo where c.ativo==true orderby c.nome select c).ToList(), "id", "nome",Emprestimo.idAmigo);
                var emprestados = (from c in contexto.emprestimo_jogo where c.status == "e" && c.idJogo!=Emprestimo.idJogo select c.Jogo).ToList();
                var jogos = (from c in contexto.Jogo where c.ativo == true orderby c.titulo select c).ToList();
                var jogosDisponiveis = jogos.Except(emprestados).ToList();
                ViewData["idJogo"] = new SelectList(jogosDisponiveis, "id", "titulo",Emprestimo.idJogo);
                
            return View(Emprestimo);
            }
            catch (Exception e)
            {
                return RedirectToAction("ListaEmprestimos");
            }
        }

        [HttpPost]
        public ActionResult EditaEmprestimo(emprestimo_jogo Emprestimo)
        {
            try
            {
                Emprestimo.status = "e";
                contexto.Entry(Emprestimo).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                TempData["sucess"] = "Emprestimo atualizado com sucesso";

            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao atualizar o cadastro do Emprestimo!";
            }

        
            return RedirectToAction("ListaEmprestimos");

        }

        [HttpPost]
        public ActionResult ExcluiEmprestimo(string idExcluir) {

            try {
                int id = int.Parse(idExcluir);
                var emprestimo = contexto.emprestimo_jogo.Find(id);
                string amigo = emprestimo.Amigo.nome;
                string tituloJogo = emprestimo.Jogo.titulo;
                contexto.emprestimo_jogo.Remove(emprestimo);
                contexto.SaveChanges();
                TempData["sucess"] = "Emprestimo " + amigo  + " - "+ tituloJogo + " foi excluído com sucesso";
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao excluir o cadastro do Emprestimo!";
            }

            return RedirectToAction("ListaEmprestimos");
        }

        [HttpPost]
        public ActionResult DevolverEmprestimo(string idDevolucao)
        {

            try
            {
                int id = int.Parse(idDevolucao);
                var emprestimo = contexto.emprestimo_jogo.Find(id);
                emprestimo.status = "d";
                contexto.Entry(emprestimo).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                TempData["sucess"] = "Emprestimo " + emprestimo.Amigo.nome + " - " + emprestimo.Jogo.titulo + " foi devolvido com sucesso";
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao excluir o cadastro do Emprestimo!";
            }

            return RedirectToAction("ListaEmprestimos");
        }

        [HttpGet]
        public ActionResult ListaEmprestimos()
        {
            try
            {
                var Emprestimos = (from c in contexto.emprestimo_jogo where c.status== "e" orderby c.data descending select c).ToList();
                return View(Emprestimos);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public ActionResult HistoricoEmprestimos()
        {
            try
            {
                var Emprestimos = (from c in contexto.emprestimo_jogo orderby c.data descending select c).ToList();
                return View(Emprestimos);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

EmprestimosJogos/Controllers/JogoController.cs
using EmprestimosJogos.Filters;
using EmprestimosJogos.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EmprestimosJogos.Controllers
{
    [FilterUsuario]
    public class JogoController : Controller
    {
        EmprestimoContext contexto;
        public JogoController() {
            contexto = new EmprestimoContext();
        }
        [HttpGet]
        public ActionResult AdicionaJogo()
        {
            try
            {
                Jogo Jogo = new Jogo();
                return View(Jogo);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult AdicionaJogo(Jogo Jogo){
            try {
                Jogo.ativo = true;
            contexto.Jogo.Add(Jogo);
            contexto.SaveChanges();
            TempData["sucess"] = "Jogo salvo com sucesso";
            
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao salvar o Jogo";
            }
            return RedirectToAction("ListaJogos");
        }

        [HttpGet]
        public ActionResult EditaJogo(int id)
        {
            try { 
            Jogo Jogo = (from c in contexto.Jogo where c.id==id select c).SingleOrDefault();
            return View(Jogo);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult EditaJogo(Jogo Jogo)
        {
            try
            {
                Jogo.ativo = true;
                contexto.Entry(Jogo).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                TempData["sucess"] = "Jogo salvo com sucesso";

            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao atualizar o cadastro do Jogo!";
            }

        
            return RedirectToAction("ListaJogos");

        }

    
        [HttpPost]
        public ActionResult ExcluiJogo(string idExcluir) {
            try
            {
                int id = int.Parse(idExcluir);
                var jogo = contexto.Jogo.Find(id);
                jogo.ativo = false;
                contexto.Entry(jogo).State = System.Data.Entity.EntityState.Modified;
                contexto.SaveChanges();
                TempData["sucess"] = "Jogo " + jogo.titulo + " foi excluído com sucesso";
            }
            catch (Exception e)
            {
                TempData["error"] = "Erro ao excluir o cadastro do jogo!";
            }

            return RedirectToAction("ListaJogos");
        }

        [HttpGet]
        public ActionResult ListaJogos()
        {
            try
            {
                var Jogos = (from c in contexto.Jogo where c.ativo==true orderby c.titulo select c).ToList();
                return View(Jogos);
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

EmprestimosJogos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de Empréstimos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.mask.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistemas de Empréstimos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if (Session["usuarioLogado"] != null)
            {
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro de Jogos", "ListaJogos", "Jogo")</li>
                    <li>@Html.ActionLink("Cadastro de Amigos", "ListaAmigos", "Amigo")</li>
                    <li>@Html.ActionLink("Cadastro de Empréstimos", "ListaEmprestimos", "Emprestimo")</li>
                    <li>@Html.ActionLink("Histórico de Empréstimos", "HistoricoEmprestimos", "Emprestimo")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
            }
        </div>
    </div>
    <div class="container body-content">
        <div id="mensagens" align="center">
            <br/>
            @if (TempData["error"] != null)
            {
                <div align="center" class="alert alert-danger fade in" style="width:40%">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <b>@TempData["error"]</b>
                </div>
            }
            else if (TempData["warning"] != null)
            {
                <div align="center" class="alert alert-warning fade in" style="width:40%">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <b>@TempData["warning"]</b>
                </div>
            }
            else if (TempData["sucess"] != null)
            {
                <div align="center" class="alert alert-success fade in" style="width:40%">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <b>@TempData["sucess"]</b>
                </div>
            }
        </div>

        @RenderBody()
        <hr />
        <footer>
            <div align="center">
                <p>&copy; @DateTime.Now.Year - Sistema de Empréstimos</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000);


</script>